language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

install:
  - travis_retry composer install --no-interaction --prefer-dist
  - travis_retry composer require --no-interaction --prefer-dist --dev php-coveralls/php-coveralls

script: vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml

after_success: php vendor/bin/php-coveralls --verbose
